# Generated by Django 3.0.4 on 2020-03-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('powiat', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('sick', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
    ]
