# Generated by Django 3.0.4 on 2020-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo', models.CharField(max_length=150)),
                ('powiat', models.CharField(max_length=150)),
                ('sick', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('wojewodztwo', models.CharField(max_length=150)),
                ('powiat', models.CharField(max_length=150)),
                ('sick', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
